import {
    MONALISA_GRID_IMAGE1,
    MONALISA_GRID_IMAGE2,
    MONALISA_GRID_IMAGE3,
    MONALISA_GRID_IMAGE4,
    MONALISA_GRID_IMAGE5,
    MONALISA_GRID_IMAGE6,
    MONALISA_GRID_IMAGE7,
    MONALISA_GRID_IMAGE8,
    MONALISA_GRID_IMAGE9,
  } from "./images";


  export const monalisaImagesStrip = [
    MONALISA_GRID_IMAGE1,
    MONALISA_GRID_IMAGE2,
    MONALISA_GRID_IMAGE3,
    MONALISA_GRID_IMAGE4,
    MONALISA_GRID_IMAGE5,
    MONALISA_GRID_IMAGE6,
    MONALISA_GRID_IMAGE7,
    MONALISA_GRID_IMAGE8,
    MONALISA_GRID_IMAGE9,
  ];